# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-16 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('year', models.IntegerField()),
                ('bureau', models.CharField(max_length=56)),
                ('head', models.CharField(max_length=256)),
                ('head_number', models.IntegerField()),
                ('sub_head', models.CharField(max_length=256)),
                ('sub_head_number', models.IntegerField(null=True)),
                ('controlling_officer_title', models.CharField(max_length=256)),
                ('controlling_officer_name', models.CharField(max_length=256)),
                ('programme', models.CharField(max_length=256)),
                ('reply_serial_no', models.CharField(max_length=256)),
                ('member', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('member_question_no', models.IntegerField()),
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
