# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='keywords',
            field=models.ManyToManyField(to='main.Keyword'),
        ),
    ]
